import Testing
import Foundation
@testable import ReticulumPackets
import ReticulumCrypto

// Announce Packet Protocol Compatibility Tests
//
// These tests verify byte-for-byte binary compatibility between the Swift
// AnnouncePayload implementation and the Python RNS reference implementation.
//
// Fixtures are generated by:
//   python Tests/Scripts/generate_fixtures.py
//
// Announce payload wire layout (bytes after the 19-byte PacketHeader):
//
//   Bytes   0– 63 : identity public key (64 bytes = X25519 pub 32B + Ed25519 pub 32B)
//   Bytes  64– 73 : name hash           (10 bytes = SHA-256(dest_full_name)[0:10])
//   Bytes  74– 83 : random hash         (10 bytes, random nonce)
//   Bytes  84–147 : Ed25519 signature   (64 bytes)
//   Bytes 148+    : app data            (variable, may be empty)
//
// Signed data (what Python signs):
//   destination_hash (16B) + identity_public_key (64B) +
//   name_hash (10B) + random_hash (10B) [+ app_data if present]
//
// NOTE: The fixture's sub-field extractions (name_hash_in_raw_hex,
// signature_in_raw_hex, etc.) contain an off-by-one error in the Python
// generator — they are NOT used here.  All expected values are derived
// directly from expected.raw_hex using the protocol-specified byte offsets.
//
// Tests FAIL until AnnouncePayload is implemented in ReticulumPackets.

// Helpers

private func loadAnnounceFixture(name: String) throws -> [String: Any] {
    try FixtureLoader.load(subdir: "announces", name: "\(name).json")
}

/// Extracts the announce payload fields from the raw packet bytes at known offsets.
private struct RawAnnounceOffsets {
    static let publicKeyStart    = 0
    static let publicKeyEnd      = 64
    static let nameHashStart     = 64
    static let nameHashEnd       = 74
    static let randomHashStart   = 74
    static let randomHashEnd     = 84
    static let signatureStart    = 84
    static let signatureEnd      = 148
    static let appDataStart      = 148
    static let minimumPayload    = 148
}

// AnnouncePayload Parsing

@Suite("AnnouncePayload — Parsing")
struct AnnouncePayloadParseTests {

    @Test("parse() returns an AnnouncePayload without throwing")
    func parseSucceeds() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        _ = try AnnouncePayload.parse(from: payload)
    }

    @Test("identityPublicKey is exactly 64 bytes")
    func identityPublicKeyLength() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.identityPublicKey.count == 64,
                "identityPublicKey should be 64 bytes, got \(announce.identityPublicKey.count)")
    }

    @Test("identityPublicKey matches Python fixture identity_public_key_hex")
    func identityPublicKeyMatchesFixture() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let expected  = try fixture.hexData(at: "inputs.identity_public_key_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        #expect(announce.identityPublicKey == expected,
                "identityPublicKey mismatch — expected \(expected.hexString), got \(announce.identityPublicKey.hexString)")
    }

    @Test("nameHash is exactly 10 bytes")
    func nameHashLength() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.nameHash.count == 10,
                "nameHash should be 10 bytes, got \(announce.nameHash.count)")
    }

    @Test("nameHash matches bytes extracted at known offset from raw_hex")
    func nameHashMatchesRawHexOffset() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let expected = Data(payload[RawAnnounceOffsets.nameHashStart ..< RawAnnounceOffsets.nameHashEnd])
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.nameHash == expected,
                "nameHash mismatch — expected \(expected.hexString), got \(announce.nameHash.hexString)")
    }

    @Test("randomHash is exactly 10 bytes")
    func randomHashLength() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.randomHash.count == 10,
                "randomHash should be 10 bytes, got \(announce.randomHash.count)")
    }

    @Test("randomHash matches bytes extracted at known offset from raw_hex")
    func randomHashMatchesRawHexOffset() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let expected = Data(payload[RawAnnounceOffsets.randomHashStart ..< RawAnnounceOffsets.randomHashEnd])
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.randomHash == expected,
                "randomHash mismatch — expected \(expected.hexString), got \(announce.randomHash.hexString)")
    }

    @Test("signature is exactly 64 bytes")
    func signatureLength() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.signature.count == 64,
                "signature should be 64 bytes, got \(announce.signature.count)")
    }

    @Test("signature matches bytes extracted at known offset from raw_hex")
    func signatureMatchesRawHexOffset() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let expected = Data(payload[RawAnnounceOffsets.signatureStart ..< RawAnnounceOffsets.signatureEnd])
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.signature == expected,
                "signature mismatch — expected \(expected.hexString), got \(announce.signature.hexString)")
    }

    @Test("appData matches Python fixture inputs.app_data_hex")
    func appDataMatchesFixture() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let expected = try fixture.hexData(at: "inputs.app_data_hex")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce = try AnnouncePayload.parse(from: payload)
        #expect(announce.appData == expected,
                "appData mismatch — expected \(expected.hexString), got \(announce.appData.hexString)")
    }

    @Test("appData decodes to UTF-8 'hello'")
    func appDataDecodesUTF8() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let expected = try fixture.string(at: "inputs.app_data_utf8")
        let payload  = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce = try AnnouncePayload.parse(from: payload)
        let decoded  = String(bytes: announce.appData, encoding: .utf8)
        #expect(decoded == expected,
                "appData UTF-8 mismatch — expected \"\(expected)\", got \"\(decoded ?? "<nil>")\"")
    }

    @Test("parse() with exactly 148 bytes (no app data) produces empty appData")
    func parseWithNoAppData() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let fullPayload = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let minPayload  = Data(fullPayload.prefix(RawAnnounceOffsets.minimumPayload))
        let announce    = try AnnouncePayload.parse(from: minPayload)
        #expect(announce.appData.isEmpty,
                "appData should be empty for minimum-length payload, got \(announce.appData.hexString)")
    }
}

// Signature Verification

@Suite("AnnouncePayload — Signature Verification")
struct AnnounceSignatureVerificationTests {

    @Test("verifySignature() returns true for Python-generated announce")
    func verifySignaturePassesForPythonAnnounce() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let valid     = announce.verifySignature(destinationHash: destHash)
        #expect(valid == true,
                "verifySignature() should return true for a valid Python-generated announce")
    }

    @Test("signedData() produces the correct 105-byte signed payload")
    func signedDataCorrectLength() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let appData   = try fixture.hexData(at: "inputs.app_data_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let signed    = announce.signedData(destinationHash: destHash)
        // 16 (dest_hash) + 64 (pub_key) + 10 (name_hash) + 10 (random_hash) + app_data.count
        let expected  = 16 + 64 + 10 + 10 + appData.count
        #expect(signed.count == expected,
                "signedData length mismatch — expected \(expected), got \(signed.count)")
    }

    @Test("signedData() starts with the destination hash")
    func signedDataStartsWithDestHash() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let signed    = announce.signedData(destinationHash: destHash)
        let prefix    = Data(signed.prefix(16))
        #expect(prefix == destHash,
                "signedData should start with dest hash — expected \(destHash.hexString), got \(prefix.hexString)")
    }

    @Test("signedData() ends with the app data bytes")
    func signedDataEndsWithAppData() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let appData   = try fixture.hexData(at: "inputs.app_data_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let signed    = announce.signedData(destinationHash: destHash)
        let suffix    = Data(signed.suffix(appData.count))
        #expect(suffix == appData,
                "signedData should end with app data — expected \(appData.hexString), got \(suffix.hexString)")
    }

    @Test("signature verifies via Identity.verify() using the Ed25519 public key")
    func verifyViaIdentity() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let pubKeyHex = try fixture.hexData(at: "inputs.identity_public_key_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let identity  = try Identity(publicKey: pubKeyHex)
        let signed    = announce.signedData(destinationHash: destHash)
        let valid     = identity.verify(signed, signature: announce.signature)
        #expect(valid == true,
                "Identity.verify() should return true for a valid Python-generated announce signature")
    }

    @Test("verifySignature() returns false for a wrong destination hash")
    func verifyFailsForWrongDestHash() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let wrongHash = Data(repeating: 0xff, count: 16)
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let valid     = announce.verifySignature(destinationHash: wrongHash)
        #expect(valid == false,
                "verifySignature() should return false when destination hash is wrong")
    }

    @Test("verifySignature() returns false for a zeroed signature")
    func verifyFailsForZeroSignature() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        var announce  = try AnnouncePayload.parse(from: payload)
        announce      = AnnouncePayload(
            identityPublicKey: announce.identityPublicKey,
            nameHash:          announce.nameHash,
            randomHash:        announce.randomHash,
            signature:         Data(count: 64),   // zeroed signature
            appData:           announce.appData
        )
        let valid = announce.verifySignature(destinationHash: destHash)
        #expect(valid == false,
                "verifySignature() should return false for a zeroed signature")
    }

    @Test("verifySignature() returns false for a single-bit-flipped signature")
    func verifyFailsForTamperedSignature() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        var announce  = try AnnouncePayload.parse(from: payload)
        var tampered  = announce.signature
        tampered[0]  ^= 0x01
        announce      = AnnouncePayload(
            identityPublicKey: announce.identityPublicKey,
            nameHash:          announce.nameHash,
            randomHash:        announce.randomHash,
            signature:         tampered,
            appData:           announce.appData
        )
        let valid = announce.verifySignature(destinationHash: destHash)
        #expect(valid == false,
                "verifySignature() should return false after a single-bit flip in the signature")
    }

    @Test("verifySignature() returns false for a different identity public key")
    func verifyFailsForWrongPublicKey() throws {
        let fixture    = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes   = try fixture.hexData(at: "expected.raw_hex")
        let destHash   = try fixture.hexData(at: "expected.destination_hash_hex")
        let payload    = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        var announce   = try AnnouncePayload.parse(from: payload)
        // Replace the identity public key with a different (random) 64-byte key
        let wrongPubKey = Data(repeating: 0xAB, count: 64)
        announce        = AnnouncePayload(
            identityPublicKey: wrongPubKey,
            nameHash:          announce.nameHash,
            randomHash:        announce.randomHash,
            signature:         announce.signature,
            appData:           announce.appData
        )
        let valid = announce.verifySignature(destinationHash: destHash)
        #expect(valid == false,
                "verifySignature() should return false when identity public key is wrong")
    }

    @Test("verifySignature() returns false for tampered app data")
    func verifyFailsForTamperedAppData() throws {
        let fixture   = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes  = try fixture.hexData(at: "expected.raw_hex")
        let destHash  = try fixture.hexData(at: "expected.destination_hash_hex")
        let payload   = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let announce  = try AnnouncePayload.parse(from: payload)
        let tampered  = AnnouncePayload(
            identityPublicKey: announce.identityPublicKey,
            nameHash:          announce.nameHash,
            randomHash:        announce.randomHash,
            signature:         announce.signature,
            appData:           Data("tampered".utf8)
        )
        let valid = tampered.verifySignature(destinationHash: destHash)
        #expect(valid == false,
                "verifySignature() should return false when app data has been tampered with")
    }
}

// Packet Integration

@Suite("AnnouncePayload — Packet Integration")
struct AnnouncePayloadPacketIntegrationTests {

    @Test("Packet.deserialize() + AnnouncePayload.parse() both succeed on announce_basic")
    func parseChainSucceeds() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let packet   = try Packet.deserialize(from: rawBytes)
        _ = try AnnouncePayload.parse(from: packet.payload)
    }

    @Test("Packet.header.packetType == .announce when parsed from announce_basic")
    func packetTypeIsAnnounce() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let packet   = try Packet.deserialize(from: rawBytes)
        #expect(packet.header.packetType == .announce)
    }

    @Test("Packet.header.destinationHash matches expected destination_hash_hex")
    func destinationHashFromPacketMatchesFixture() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let expected = try fixture.hexData(at: "expected.destination_hash_hex")
        let packet   = try Packet.deserialize(from: rawBytes)
        #expect(packet.header.destinationHash == expected,
                "destinationHash mismatch — expected \(expected.hexString), got \(packet.header.destinationHash.hexString)")
    }

    @Test("AnnouncePayload parsed from Packet.payload has correct identityPublicKey")
    func identityPublicKeyFromPacketPayload() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let expected = try fixture.hexData(at: "inputs.identity_public_key_hex")
        let packet   = try Packet.deserialize(from: rawBytes)
        let announce = try AnnouncePayload.parse(from: packet.payload)
        #expect(announce.identityPublicKey == expected,
                "identityPublicKey mismatch — expected \(expected.hexString), got \(announce.identityPublicKey.hexString)")
    }

    @Test("End-to-end: parse packet, parse payload, verify signature — all using Python fixture")
    func endToEndVerification() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let packet   = try Packet.deserialize(from: rawBytes)
        let announce = try AnnouncePayload.parse(from: packet.payload)
        let destHash = packet.header.destinationHash
        let valid    = announce.verifySignature(destinationHash: destHash)
        #expect(valid == true,
                "End-to-end signature verification failed for Python announce_basic fixture")
    }

    @Test("announce Packet round-trip: serialize(deserialize(raw)) == raw")
    func announcePacketRoundTrip() throws {
        let fixture  = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes = try fixture.hexData(at: "expected.raw_hex")
        let packet   = try Packet.deserialize(from: rawBytes)
        let result   = packet.serialize()
        #expect(result == rawBytes,
                "round-trip mismatch — expected \(rawBytes.hexString), got \(result.hexString)")
    }
}

// Error Handling

@Suite("AnnouncePayload — Error Handling")
struct AnnouncePayloadErrorTests {

    @Test("parse() throws when payload is shorter than 148 bytes")
    func parseThrowsOnTooShort() throws {
        let shortPayload = Data(count: 100)
        #expect(throws: (any Error).self) {
            try AnnouncePayload.parse(from: shortPayload)
        }
    }

    @Test("parse() throws on empty data")
    func parseThrowsOnEmpty() throws {
        #expect(throws: (any Error).self) {
            try AnnouncePayload.parse(from: Data())
        }
    }

    @Test("parse() throws when data is exactly 147 bytes (one byte short)")
    func parseThrowsOnOneByteShort() throws {
        let shortPayload = Data(count: RawAnnounceOffsets.minimumPayload - 1)
        #expect(throws: (any Error).self) {
            try AnnouncePayload.parse(from: shortPayload)
        }
    }

    @Test("parse() succeeds when payload is exactly 148 bytes (no app data)")
    func parseSucceedsAtMinimumLength() throws {
        let fixture     = try loadAnnounceFixture(name: "announce_basic")
        let rawBytes    = try fixture.hexData(at: "expected.raw_hex")
        let fullPayload = Data(rawBytes.dropFirst(PacketHeader.serializedLength))
        let minPayload  = Data(fullPayload.prefix(RawAnnounceOffsets.minimumPayload))
        let announce    = try AnnouncePayload.parse(from: minPayload)
        #expect(announce.appData.isEmpty)
        #expect(announce.identityPublicKey.count == 64)
        #expect(announce.nameHash.count == 10)
        #expect(announce.randomHash.count == 10)
        #expect(announce.signature.count == 64)
    }
}
