import Testing
import Foundation
import CryptoKit
@testable import ReticulumCrypto

/// Tests verifying that our ReticulumToken encrypt/decrypt is interoperable
/// with the Python RNS reference implementation.
///
/// Test vectors were generated by a Python script using:
///   - cryptography.hazmat (X25519, HKDF, AES-256-CBC)
///   - Reticulum-compatible Token format: iv(16) + ciphertext + hmac(32)
///   - Identity.encrypt format: ephemeral_pub(32) + token
@Suite("Token Interop")
struct TokenInteropTests {

    // -- Fixed test values from Python --
    let recipientX25519Priv = Data(hexString: "c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf")!
    let recipientX25519Pub  = Data(hexString: "dc2cca31e8e43bbd91dff7e475cca3347eb478107d5bd765aba4ae4a30c35d44")!
    let recipientFullPubkey = Data(hexString: "dc2cca31e8e43bbd91dff7e475cca3347eb478107d5bd765aba4ae4a30c35d440000000000000000000000000000000000000000000000000000000000000000")!
    let expectedIdentityHash = Data(hexString: "a72dfe3ba1f156cb874a464c123fb84c")!
    let expectedSharedSecret = Data(hexString: "28150aa20f6f6c9c8177b9deded7464ebc5aac96029777ff7503cd8e8ca7143e")!
    let expectedDerivedKey   = Data(hexString: "7dfbd80ed753abe167f71149795a559edd1d02d108daf9def5f5a61a487937b8db186109238b629497de972a1fac2373d8eb94259218e768bf6eadf191116cf1")!
    let pythonToken          = Data(hexString: "736845d54e87de09d6bb114aa7042c50a4a015bd9901d1a0026f5956533a151900112233445566778899aabbccddeeffc0212b187bef03403d2988006b806d8eca00c91d47fec23cbeb5bb970f219867f0ce6d6082403492970a257f0f383e65")!
    let expectedPlaintext    = Data(hexString: "48656c6c6f205265746963756c756d")! // "Hello Reticulum"

    @Test("Identity hash matches Python")
    func identityHash() {
        let hash = Hashing.truncatedHash(recipientFullPubkey, length: 16)
        #expect(hash == expectedIdentityHash)
    }

    @Test("HKDF derivation matches Python")
    func hkdfDerivation() throws {
        // Reproduce HKDF with the known shared secret
        let sharedSecret = try Curve25519.KeyAgreement.PrivateKey(
            rawRepresentation: Data(hexString: "e0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff")!
        ).sharedSecretFromKeyAgreement(
            with: Curve25519.KeyAgreement.PublicKey(rawRepresentation: recipientX25519Pub)
        )

        let derived = sharedSecret.hkdfDerivedSymmetricKey(
            using: SHA256.self,
            salt: expectedIdentityHash,
            sharedInfo: Data(),
            outputByteCount: 64
        )
        let derivedBytes = derived.withUnsafeBytes { Data($0) }
        #expect(derivedBytes == expectedDerivedKey)
    }

    @Test("Decrypt Python-produced token")
    func decryptPythonToken() throws {
        let plaintext = try ReticulumToken.decrypt(
            pythonToken,
            recipientX25519PrivateKey: recipientX25519Priv,
            identityHash: expectedIdentityHash
        )
        #expect(plaintext == expectedPlaintext)
        #expect(String(data: plaintext, encoding: .utf8) == "Hello Reticulum")
    }

    @Test("Encrypt then decrypt round-trip")
    func encryptDecryptRoundTrip() throws {
        let message = Data("Hello from Swift!".utf8)

        let encrypted = try ReticulumToken.encrypt(
            message,
            recipientX25519PublicKey: recipientX25519Pub,
            identityHash: expectedIdentityHash
        )

        // Token format: ephemeral_pub(32) + iv(16) + ciphertext + hmac(32)
        #expect(encrypted.count >= 80 + 16) // minimum: 32+16+16+32 = 96

        let decrypted = try ReticulumToken.decrypt(
            encrypted,
            recipientX25519PrivateKey: recipientX25519Priv,
            identityHash: expectedIdentityHash
        )
        #expect(decrypted == message)
    }

    @Test("Swift-encrypted token structure matches Python format")
    func tokenStructure() throws {
        let message = Data("test".utf8)
        let encrypted = try ReticulumToken.encrypt(
            message,
            recipientX25519PublicKey: recipientX25519Pub,
            identityHash: expectedIdentityHash
        )

        // ephemeral_pub(32) + iv(16) + ciphertext(16, one AES block) + hmac(32) = 96
        #expect(encrypted.count == 96)

        // Verify the structure by decrypting with Python-compatible key
        let decrypted = try ReticulumToken.decrypt(
            encrypted,
            recipientX25519PrivateKey: recipientX25519Priv,
            identityHash: expectedIdentityHash
        )
        #expect(decrypted == message)
    }
}
