import Testing
import Foundation
@testable import LXMF
@testable import ReticulumCrypto

// LXMF Compatibility Oracle Tests
//
// Verifies that Swift LXMFMessage produces byte-identical output to the
// Python LXMF reference implementation (tested against lxmf 0.9.4 / rns 1.1.3).
//
// Fixture: Tests/ProtocolFixtures/lxmf/message_basic.json
// Generated by: Tests/Scripts/generate_fixtures.py
//
// Wire format (packed bytes):
//   [destinationHash: 16 bytes]
//   [sourceHash:      16 bytes]
//   [signature:       64 bytes]  Ed25519 over signedPart
//   [msgpackPayload:  variable]  msgpack([timestamp, title, content, fields])
//
// where:
//   messageHash = SHA-256(destinationHash + sourceHash + msgpackPayload)
//   signedPart  = destinationHash + sourceHash + msgpackPayload + messageHash
//
// Tests FAIL until LXMFMessage is fully implemented.

// Helper

private func loadBasicFixture() throws -> [String: Any] {
    try FixtureLoader.load(subdir: "lxmf", name: "message_basic.json")
}

// Envelope Parsing

@Suite("LXMF — Envelope Parsing")
struct LXMFEnvelopeParsingTests {

    @Test("message_basic: parse does not throw")
    func parseDoesNotThrow() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        _ = try LXMFMessage(packed: packed)
    }

    @Test("message_basic: packed size is 139 bytes")
    func packedSizeIs139() throws {
        let fixture = try loadBasicFixture()
        let expected = try fixture.int(at: "expected.packed_size")
        let packed = try fixture.hexData(at: "expected.packed_hex")
        #expect(packed.count == expected,
                "Expected packed size \(expected), got \(packed.count)")
    }

    @Test("message_basic: destinationHash is 16 bytes and matches fixture")
    func destinationHashMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.hexData(at: "expected.destination_hash_in_packed_hex")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.destinationHash.count == 16,
                "destinationHash must be 16 bytes, got \(msg.destinationHash.count)")
        #expect(msg.destinationHash == expected,
                "destinationHash mismatch: expected \(expected.hexString), got \(msg.destinationHash.hexString)")
    }

    @Test("message_basic: sourceHash is 16 bytes and matches fixture")
    func sourceHashMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.hexData(at: "expected.source_hash_in_packed_hex")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.sourceHash.count == 16,
                "sourceHash must be 16 bytes, got \(msg.sourceHash.count)")
        #expect(msg.sourceHash == expected,
                "sourceHash mismatch: expected \(expected.hexString), got \(msg.sourceHash.hexString)")
    }

    @Test("message_basic: signature is 64 bytes and matches fixture")
    func signatureMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.hexData(at: "expected.signature_in_packed_hex")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.signature.count == 64,
                "signature must be 64 bytes, got \(msg.signature.count)")
        #expect(msg.signature == expected,
                "signature mismatch: expected \(expected.hexString), got \(msg.signature.hexString)")
    }

    @Test("message_basic: msgpackPayload matches fixture")
    func msgpackPayloadMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.hexData(at: "expected.msgpack_payload_hex")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.msgpackPayload == expected,
                "msgpackPayload mismatch: expected \(expected.hexString), got \(msg.msgpackPayload.hexString)")
    }
}

// Payload Decoding

@Suite("LXMF — Payload Decoding")
struct LXMFPayloadDecodingTests {

    @Test("message_basic: timestamp matches fixture (1700000000.0)")
    func timestampMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.double(at: "inputs.timestamp_unix")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.timestamp == expected,
                "timestamp mismatch: expected \(expected), got \(msg.timestamp)")
    }

    @Test("message_basic: title matches fixture (\"Test Title\")")
    func titleMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.string(at: "inputs.title_utf8")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.title == expected,
                "title mismatch: expected \"\(expected)\", got \"\(msg.title)\"")
    }

    @Test("message_basic: content matches fixture (\"Hello from fixture\")")
    func contentMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expected = try fixture.string(at: "inputs.content_utf8")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.content == expected,
                "content mismatch: expected \"\(expected)\", got \"\(msg.content)\"")
    }

    @Test("message_basic: fields are empty")
    func fieldsAreEmpty() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.fields.isEmpty, "fields should be empty, got \(msg.fields.count) entries")
    }
}

// Message Hash

@Suite("LXMF — Message Hash")
struct LXMFMessageHashTests {

    /// Python: RNS.Identity.full_hash(dest + src + packed_payload) = 32-byte SHA-256
    @Test("message_basic: message hash matches SHA-256(dest+src+payload)")
    func messageHashMatchesFixture() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")
        let expectedHash = try fixture.hexData(at: "expected.message_hash_hex")

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.hash.count == 32,
                "message hash must be 32 bytes (full SHA-256), got \(msg.hash.count)")
        #expect(msg.hash == expectedHash,
                "message hash mismatch: expected \(expectedHash.hexString), got \(msg.hash.hexString)")
    }
}

// Signature Verification

@Suite("LXMF — Signature Verification")
struct LXMFSignatureVerificationTests {

    /// The Ed25519 public key is bytes [32:64] of the RNS identity public key.
    /// Signed data = destinationHash + sourceHash + msgpackPayload + messageHash
    @Test("message_basic: signature verifies with source identity Ed25519 public key")
    func signatureVerifiesWithSourceKey() throws {
        let fixture = try loadBasicFixture()
        let packed = try fixture.hexData(at: "expected.packed_hex")

        // RNS identity public key layout: [0:32] = X25519, [32:64] = Ed25519
        let identityKey = try fixture.hexData(at: "inputs.source_identity_key_hex")
        #expect(identityKey.count == 64,
                "identity public key must be 64 bytes, got \(identityKey.count)")

        let ed25519PublicKey = identityKey.subdata(in: 32..<64)  // bytes [32:64]

        let msg = try LXMFMessage(packed: packed)
        #expect(msg.verifySignature(ed25519PublicKey: ed25519PublicKey),
                "Ed25519 signature verification failed for message_basic fixture")
    }
}

// Round-Trip Serialization

@Suite("LXMF — Serialization")
struct LXMFSerializationTests {

    /// Re-serializes a parsed message and verifies byte-identical output.
    /// This validates both parsing and serialization against Python LXMF.
    @Test("message_basic: pack() produces byte-identical output to Python")
    func packProducesByteIdenticalOutput() throws {
        let fixture = try loadBasicFixture()
        let expectedPacked = try fixture.hexData(at: "expected.packed_hex")

        let msg = try LXMFMessage(packed: expectedPacked)
        let repacked = try msg.pack()

        #expect(repacked == expectedPacked,
                """
                pack() round-trip mismatch:
                  expected: \(expectedPacked.hexString)
                  got:      \(repacked.hexString)
                """)
    }
}

@Suite("LXMF — Stamp Semantics")
struct LXMFStampSemanticsTests {

    @Test("Hash/signature use canonical payload when stamp present")
    func stampedMessageUsesCanonicalHashAndSignature() throws {
        let sender = try Identity.generate()
        let recipient = try Identity.generate()
        let destinationHash = Destination.hash(
            appName: "lxmf",
            aspects: ["delivery"],
            identityHash: recipient.hash
        )

        let packed = try LXMFMessage.create(
            destinationHash: destinationHash,
            sourceIdentity: sender,
            content: "stamp check",
            title: "s",
            timestamp: 1_700_000_100.0,
            stampCost: 6
        )

        let parsed = try LXMFMessage(packed: packed)
        #expect(parsed.stamp != nil)
        #expect(parsed.msgpackPayload != parsed.canonicalMsgpackPayload)
        let senderEd25519 = Data(sender.publicKey[32..<64])
        #expect(parsed.verifySignature(ed25519PublicKey: senderEd25519))
    }

    @Test("Ticket stamp validates and sets ticket cost sentinel")
    func ticketStampValidation() throws {
        let sender = try Identity.generate()
        let recipient = try Identity.generate()
        let destinationHash = Destination.hash(
            appName: "lxmf",
            aspects: ["delivery"],
            identityHash: recipient.hash
        )
        let ticket = Data(repeating: 0xAB, count: 16)

        let packed = try LXMFMessage.create(
            destinationHash: destinationHash,
            sourceIdentity: sender,
            content: "ticket stamp",
            title: "",
            timestamp: 1_700_000_200.0,
            outboundTicket: ticket
        )

        let parsed = try LXMFMessage(packed: packed)
        #expect(parsed.stamp?.count == 16)
        let validation = parsed.validateStamp(targetCost: 10, tickets: [ticket])
        #expect(validation.valid)
        #expect(validation.value == LXMFMessage.ticketStampValue)
    }
}
